### ISSUE TITLE
AttributeError: GoogleResult instance has no attribute 'number_of_results'

### ISSUE THREAD

**Issue by ckeenan34** [abenassi/Google-Search-API#55]
I received this error after doing the following 3 lines: 
`from google import google`
`search_results= google.search("something",1)`
`search_results[0].number_of_results`
The last line is the problem. number_of_results seems to be the only problem because a similar line of:
`search_results[0].name`
gives me the correct result. I was looking in the code and noticed number_of_results gets initialized to None so at the very leased it should return None but instead its saying number_of_results doesn't exist.

**Comment by JuaniFilardo** [comment]
Hmm. It's an error in the regular expression that matches the div containing the results (it only works for English, my bad). 

I'll see what I can do to fix it. In the meantime you can use 
`search_results= google.search("something",1,ncr=True)` 
in case you don't mind searching as if you were in the USA.

**Comment by JuaniFilardo** [comment]
Fixed it. Sorry for the inconvenience, have a good one :)

**Comment by cameronbiggs** [comment]
I am still getting this issue, reproducible with the same code as above

**Comment by JuaniFilardo** [comment]
Are you sure you pulled the last commit from master? 
What was your query and from which country have you performed the search? I'm afraid this may only work for Spanish and English, but I'm pretty sure I had fixed it to make it language independent.

**Comment by cameronbiggs** [comment]
I am in the UK. I have installed the repo through Pip

**Comment by JuaniFilardo** [comment]
I think the last version has not been released through pip yet. What's happening is that you're searching for an attribute that doesn't even exist, E.g.:
```
search_results[0].pineapple 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'GoogleResult' object has no attribute 'pineapple'
```
Had you been using the last version, this error shouldn't happen. Until this is released through pip (and the problems with pip3 are fixed), you could try installing this way: #48 

Let me know if the error persists :)

**Comment by cameronbiggs** [comment]
Will do, many thanks
