### ISSUE TITLE
empty list returned from google.search for any query

### ISSUE THREAD

**Issue by hedythedev** [abenassi/Google-Search-API#88]
```python
from google import google

results = google.search("hi", 3)
print(results)
```

This prints `[]`

**Comment by nikisalli** [comment]
fixed with pr #87, rebuild the package by cloning this repo

don't forget that the package name was changed from google to googleapi to solve naming conflicts

**Comment by katesaikishore** [comment]
I am still getting an empty array I have cloned the latest repo 
`pip install git+https://github.com/abenassi/Google-Search-API`
and upgraded

**Comment by Woolwit** [comment]
Empty array here as well.
